##### This is for generating WordClouds based on the NGRAMS API and using Z-scores

In [87]:
#pip install stopwordsiso

In [88]:
#importing libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from collections import Counter
import time
from stopwordsiso import stopwords
import re

In [89]:
#loading the data

df = pd.read_csv('evaluation_results3.csv')
df.head(5)

,ID,Data Provider,Project Name,Consumer Team,Consumer Name,Consumer Description,Variation Type,Variation Value,Purpose,Realistic?,Decision,AI Decision 1,AI Decision 2,AI Decision 3,AI Warning 1,AI Warning 2,AI Warning 3,Vote Count,Final AI Decision
0,8392a6d9159cc8a43f7794b73694e375edddcaecc8afb2...,Benefit,Claims Risk Pattern Analysis,underwriting,Risk Insight Tool,A platform designed to offer in-depth risk ins...,NaN,Original Request,"To improve our risk assessment process, we aim...","Yes, this is a realistic access request for a ...",Accept,Accept,Accept,Accept,NaN,NaN,NaN,3-0,Accept
1,8392a6d9159cc8a43f7794b73694e375edddcaecc8afb2...,Benefit,Claims Risk Pattern Analysis,underwriting,Risk Insight Tool,A platform designed to offer in-depth risk ins...,combined,"intern + very hasty (typos, shorthand, missing...",hey need access to old claims data asap gotta ...,NaN,NaN,Reject,Reject,Reject,"{'title': 'Default policies', 'policyKey': 'gl...","{'policyKey': 'Default policies', 'title': 'Da...","{'policyKey': 'default', 'title': 'Default pol...",0-3,Reject
2,8392a6d9159cc8a43f7794b73694e375edddcaecc8afb2...,Benefit,Claims Risk Pattern Analysis,underwriting,Risk Insight Tool,A platform designed to offer in-depth risk ins...,combined,"intern + neutral (standard professional, no pa...",I'm looking to access historical claims data t...,NaN,NaN,Accept,Accept,Accept,NaN,NaN,NaN,3-0,Accept
3,8392a6d9159cc8a43f7794b73694e375edddcaecc8afb2...,Benefit,Claims Risk Pattern Analysis,underwriting,Risk Insight Tool,A platform designed to offer in-depth risk ins...,combined,intern + very formal (precise legal-style lang...,I hereby formally request access to the histor...,NaN,NaN,Accept,Accept,Accept,NaN,NaN,NaN,3-0,Accept
4,8392a6d9159cc8a43f7794b73694e375edddcaecc8afb2...,Benefit,Claims Risk Pattern Analysis,underwriting,Risk Insight Tool,A platform designed to offer in-depth risk ins...,combined,"junior analyst + very hasty (typos, shorthand,...",hey can I get access to the old claims data? n...,NaN,NaN,Reject,Reject,Reject,"{'policyKey': 'Default policies', 'title': 'Da...","{'policyKey': 'Default policies', 'title': 'Da...","{'policyKey': 'Default policies', 'title': 'Da...",0-3,Reject

In [90]:
#extracting columns for the seniority and the hastiness dimension.

def extracting_seniority(text):
    text = str(text).lower()

    if "intern" in text:
        return "Intern"
    elif "junior analyst" in text:
        return "Junior Analyst"
    elif "senior manager" in text:
        return "Senior Manager"
    elif "executive/ceo" in text:
        return "Executive/CEO"
    #elif "original request" in text:
    #    return "Original"
    return None


def extracting_hastiness(text):
    text = str(text).lower()

    if "very hasty" in text:
        return "Very Hasty"
    elif "neutral" in text:
        return "Neutral"
    elif "very formal" in text:
        return "Very Formal"
    #elif "original request" in text:
        #return "Original"
    return None

df['Seniority'] = df['Variation Value'].apply(extracting_seniority)
df['Hastiness'] = df['Variation Value'].apply(extracting_hastiness)



seniority_category=["Intern", "Junior Analyst", "Senior Manager", "Executive/CEO", "Original"]
hastiness_category=["Very Hasty", "Neutral", "Very Formal", "Original"]

df["Seniority"] = pd.Categorical(df["Seniority"],categories = seniority_category, ordered=True)
df["Hastiness"] = pd.Categorical(df["Hastiness"],categories = hastiness_category, ordered=True)

In [91]:
#cleaning the text and tokenising it (removing punctuation etc.)

def tokenise(text):
    if pd.isna(text):
        return []
    text = str(text).lower()
    text = re.sub(r"[^\w\s]", "", text) #removing any punctuation from the prompt
    text = re.sub(r"http\S+", "", text) #removing any URLs from the prompt if there's any
    text = re.sub(r"\s+", " ", text) #removing any extra whitespace

    words = text.split() #splitting the text into words

    return words

#applying the tokenis into the purpose column
df["Tokens"] = (df["Purpose"].apply(tokenise))

#checking if it works
df[['Purpose', 'Tokens']].head(5)

,Purpose,Tokens
0,"To improve our risk assessment process, we aim...","[to, improve, our, risk, assessment, process, ..."
1,hey need access to old claims data asap gotta ...,"[hey, need, access, to, old, claims, data, asa..."
2,I'm looking to access historical claims data t...,"[im, looking, to, access, historical, claims, ..."
3,I hereby formally request access to the histor...,"[i, hereby, formally, request, access, to, the..."
4,hey can I get access to the old claims data? n...,"[hey, can, i, get, access, to, the, old, claim..."

In [92]:
print(df["Tokens"].iloc[1])

['hey', 'need', 'access', 'to', 'old', 'claims', 'data', 'asap', 'gotta', 'check', 'out', 'risk', 'patterns', 'tied', 'to', 'diff', 'groups', 'and', 'actions', 'wanna', 'use', 'beneficiaries', 'info', 'to', 'make', 'risk', 'profiles', 'for', 'various', 'customer', 'types', 'thisll', 'help', 'us', 'tweak', 'underwriting', 'and', 'predict', 'premiums', 'better', 'for', 'upcoming', 'policies', 'goal', 'is', 'to', 'make', 'sure', 'our', 'policies', 'match', 'real', 'risk', 'so', 'it', 'helps', 'the', 'company', 'with', 'better', 'financial', 'guesses', 'and', 'gives', 'customers', 'fair', 'insurance', 'prices', 'thx']

In [93]:
#calculating the word frequencies, using the Counter library to count the words

from collections import Counter

def get_word_frequencies(df):
    all_words = []

    for tokens in df["Tokens"]:
        all_words.extend(tokens)

    word_counts = Counter(all_words)

    frequency_df = pd.DataFrame(word_counts.items(),columns=["Word", "Count"])

    total_words = frequency_df["Count"].sum()
    frequency_df["Relative Frequency"] = (frequency_df["Count"] / total_words)

    return frequency_df.sort_values(by="Count",ascending=False).reset_index(drop=True)

In [94]:
#applying the word frequency function to the different hastiness categories
very_hasty_words = df[df["Hastiness"] == "Very Hasty"]
very_formal_words = df[df["Hastiness"] == "Very Formal"]
neutral_words = df[df["Hastiness"] == "Neutral"]


very_hasty_word_freq = get_word_frequencies(very_hasty_words)
very_formal_word_freq = get_word_frequencies(very_formal_words)
neutral_word_freq = get_word_frequencies(neutral_words)


#displaying a table of the common words in the different hastiness categories

print("Very Hasty Word Frequencies:")
print(f"Total Words in Very Hasty: {very_hasty_word_freq['Count'].sum()}")
print(f"Total Unique Words in Very Hasty: {len(very_hasty_word_freq)}")
display(very_hasty_word_freq.head(10))
print()

print("Very Formal Word Frequencies:")
print(f"Total Words in Very Formal: {very_formal_word_freq['Count'].sum()}")
print(f"Total Unique Words in Very Formal: {len(very_formal_word_freq)}")
display(very_formal_word_freq.head(10))
print()

print("Neutral Word Frequencies:")
print(f"Total Words in Neutral: {neutral_word_freq['Count'].sum()}")
print(f"Total Unique Words in Neutral: {len(neutral_word_freq)}")
display(neutral_word_freq.head(10))

Very Hasty Word Frequencies:
Total Words in Very Hasty: 18748
Total Unique Words in Very Hasty: 1442

   Word  Count  Relative Frequency
0    to    803            0.042831
1  need    454            0.024216
2   and    443            0.023629
3  data    433            0.023096
4   the    339            0.018082
5    we    284            0.015148
6     n    266            0.014188
7   can    265            0.014135
8   our    255            0.013601
9   hey    254            0.013548

Very Formal Word Frequencies:
Total Words in Very Formal: 32757
Total Unique Words in Very Formal: 1558

     Word  Count  Relative Frequency
0     the   2027            0.061880
1      to   1942            0.059285
2      of   1461            0.044601
3     and   1111            0.033916
4    this    679            0.020728
5    data    652            0.019904
6      is    612            0.018683
7     our    513            0.015661
8      in    427            0.013035
9  access    424            0.012944

Neutral Word Frequencies:
Total Words in Neutral: 25236
Total Unique Words in Neutral: 1433

     Word  Count  Relative Frequency
0      to   1535            0.060826
1     and   1111            0.044024
2     our    856            0.033920
3     the    652            0.025836
4    data    547            0.021675
5    this    524            0.020764
6  access    376            0.014899
7    will    366            0.014503
8    help    355            0.014067
9      us    352            0.013948

In [95]:
#using the NGRAM API

import requests
from urllib.parse import quote

def query_ngram(word):
    url = ("https://api.ngrams.dev/eng/search"f"?query={quote(str(word))}&flags=cr")

    try:
        response = requests.get(url, timeout=30)
        response.raise_for_status()
        return response.json()

    except requests.RequestException as error:
        print(f"API request failed for {word!r}: {error}")
        return None

wording_dict_results = query_ngram("hi") #different relTotalMatchCount for each value
display(wording_dict_results)

{'query': 'hi',
 'queryTokens': [{'text': 'hi', 'kind': 'TERM'}],
 'ngrams': [{'id': '8df4fa001ec522675b4745ec8db574f6',
   'abstract': True,
   'absTotalMatchCount': 29652674,
   'relTotalMatchCount': 1.484477740013315e-05,
   'tokens': [{'text': 'hi', 'kind': 'TERM'}]}]}

In [96]:
def get_ngram_relative_frequency(word):
    result = query_ngram(word)
    if result is None:
        return np.nan

    ngrams = result.get("ngrams", [])
    if len(ngrams) == 0:
        return 0.0

    return float(ngrams[0].get("relTotalMatchCount",0.0))

In [103]:

#querying the NGRAM baseline for the first 100 Very Hasty words

import time

very_hasty_top = very_hasty_word_freq.head(100).copy()

very_hasty_ngram_frequencies = []

for index, word in enumerate(very_hasty_top["Word"], start=1):
    frequency = get_ngram_relative_frequency(word)

    very_hasty_ngram_frequencies.append(frequency)

    print(f"{index}/100: {word} = {frequency}")

    # Small delay to avoid sending requests too rapidly
    time.sleep(0.1)

very_hasty_top["NGRAMS Relative Frequency"] = (very_hasty_ngram_frequencies)

1/100: to = 0.020195045962684514
2/100: need = 0.0002740083511912232
3/100: and = 0.023998308600294487
4/100: data = 0.0003273879521141146
5/100: the = 0.05501475193395114
6/100: we = 0.0020811429402730845
7/100: n = 0.00020321823216748255
8/100: can = 0.001538514560844412
9/100: our = 0.000914518701539268
10/100: hey = 8.549207951461519e-06
11/100: thx = 5.939578231161876e-08
12/100: for = 0.007660713853566457
13/100: access = 7.807733681251938e-05
14/100: on = 0.00513269421300439
15/100: make = 0.0005057664770330657
16/100: gotta = 1.9141928384088097e-06
17/100: so = 0.0013510108685087074
18/100: better = 0.00022134894240155874
19/100: get = 0.00031094763170706524
20/100: asap = 3.0807319303720594e-07
21/100: stuff = 1.6027104604320883e-05
22/100: how = 0.0005562113909447249
23/100: with = 0.005242616106091603
24/100: boost = 4.334172973212802e-06
25/100: us = 0.0004647327122888839
26/100: it = 0.0054602160284054424
27/100: keep = 0.00014012255629383506
28/100: wanna = 1.181167763914025e-06
29/100: customers = 3.301302276089402e-05
30/100: check = 5.74543706616031e-05
31/100: help = 0.00018203414598503623
32/100: see = 0.0008376825545509459
33/100: out = 0.001017953632426928
34/100: up = 0.0009326312006512213
35/100: marketing = 4.329986823115776e-05
36/100: order = 0.0004547343426675492
37/100: tweak = 2.2102906554583868e-07
38/100: i = 0.003954687206930095
39/100: info = 4.252229181433235e-06
40/100: customer = 2.8927292406745155e-05
41/100: this = 0.004047237281990258
42/100: spot = 3.661309982941106e-05
43/100: want = 0.00020502488842237066
44/100: risk = 9.432139341779669e-05
45/100: claims = 9.299467134418512e-05
46/100: more = 0.001423161283812431
47/100: in = 0.017455072858922904
48/100: what = 0.0010829207710590523
49/100: ppl = 2.636384956045758e-07
50/100: campaign = 3.839464088583141e-05
51/100: team = 5.257587902776954e-05
52/100: at = 0.00368274757002609
53/100: like = 0.000616485273044775
54/100: are = 0.003847906577967233
55/100: that = 0.008148557087083645
56/100: payment = 9.908263189804376e-05
57/100: thisll = 6.538121750697389e-10
58/100: campaigns = 8.464567309615257e-06
59/100: quick = 3.1589152007768405e-05
60/100: sales = 9.977037171853207e-05
61/100: product = 0.000109283233735202
62/100: any = 0.0012444377182789697
63/100: they = 0.002130610326886001
64/100: patterns = 4.487954102386123e-05
65/100: cut = 0.00010569239864720867
66/100: were = 0.002128068310656171
67/100: sure = 0.00011147386597068287
68/100: look = 0.00017692596202402623
69/100: fraud = 1.9735015125133364e-05
70/100: from = 0.0036604681617184408
71/100: helps = 1.893713348486168e-05
72/100: some = 0.001096140517822303
73/100: models = 6.0977345953162374e-05
74/100: use = 0.0006082020284769281
75/100: by = 0.005305288744461861
76/100: figure = 0.00022741658471580223
77/100: happy = 5.223098008925138e-05
78/100: down = 0.0003843204525008108
79/100: right = 0.0004329053623882006
80/100: if = 0.0015331230073776475
81/100: is = 0.008423684383745337
82/100: logistics = 4.339656284662678e-06
83/100: those = 0.0006801138463914766
84/100: fast = 5.042865671673328e-05
85/100: shipping = 2.529361860387212e-05
86/100: or = 0.004184926903056282
87/100: gonna = 4.700516049953869e-06
88/100: market = 0.0001779909234347045
89/100: a = 0.015161468752774571
90/100: itll = 1.2516047617854931e-08
91/100: past = 0.00016290198823817696
92/100: pricing = 8.952800800415766e-06
93/100: trends = 2.4743395108178668e-05
94/100: find = 0.00024746672329190657
95/100: insurance = 0.0001256235729441412
96/100: things = 0.00021445548124303913
97/100: into = 0.0010470995599253896
98/100: predict = 1.115933629115348e-05
99/100: thanks = 3.076179525307743e-05
100/100: stock = 0.0001367126644762251

In [104]:

#querying the NGRAM baseline for the first 100 Very Formal words

very_formal_top = very_formal_word_freq.head(100).copy()

very_formal_ngram_frequencies = []

for index, word in enumerate(very_formal_top["Word"], start=1):
    frequency = get_ngram_relative_frequency(word)

    very_formal_ngram_frequencies.append(frequency)

    print(f"{index}/100: {word} = {frequency}")

    # Small delay to avoid sending requests too rapidly
    time.sleep(0.1)

very_formal_top["NGRAMS Relative Frequency"] = (very_formal_ngram_frequencies)

1/100: the = 0.05501475193395114
2/100: to = 0.020195045962684514
3/100: of = 0.033448675537160015
4/100: and = 0.023998308600294487
5/100: this = 0.004047237281990258
6/100: data = 0.0003273879521141146
7/100: is = 0.008423684383745337
8/100: our = 0.000914518701539268
9/100: in = 0.017455072858922904
10/100: access = 7.807733681251938e-05
11/100: request = 7.976774215882444e-05
12/100: customer = 2.8927292406745155e-05
13/100: analysis = 0.0001945704998275812
14/100: a = 0.015161468752774571
15/100: for = 0.007660713853566457
16/100: by = 0.005305288744461861
17/100: will = 0.0017224095799333013
18/100: with = 0.005242616106091603
19/100: i = 0.003954687206930095
20/100: order = 0.0004547343426675492
21/100: that = 0.008148557087083645
22/100: marketing = 4.329986823115776e-05
23/100: team = 5.257587902776954e-05
24/100: thereby = 3.8817636336982576e-05
25/100: purpose = 0.00018457364909302992
26/100: enhance = 1.4060188772636827e-05
27/100: formally = 1.0019823771995218e-05
28/100: we = 0.0020811429402730845
29/100: strategies = 2.9427423176520038e-05
30/100: objective = 4.065056572874652e-05
31/100: risk = 9.432139341779669e-05
32/100: information = 0.00037573878572852616
33/100: campaigns = 8.464567309615257e-06
34/100: comprehensive = 3.474633841100759e-05
35/100: facilitate = 1.7007754281727953e-05
36/100: hereby = 3.297168340854443e-05
37/100: it = 0.0054602160284054424
38/100: claims = 9.299467134418512e-05
39/100: product = 0.000109283233735202
40/100: payment = 9.908263189804376e-05
41/100: satisfaction = 3.17459512861309e-05
42/100: pertaining = 1.048907868733103e-05
43/100: are = 0.003847906577967233
44/100: enable = 3.525422631681058e-05
45/100: patterns = 4.487954102386123e-05
46/100: an = 0.0028115248078374668
47/100: enhancing = 4.956323317492123e-06
48/100: on = 0.00513269421300439
49/100: potential = 9.918122887665616e-05
50/100: these = 0.001275391671233161
51/100: rates = 0.00013449801740916836
52/100: more = 0.001423161283812431
53/100: conduct = 7.008524942438986e-05
54/100: performance = 0.00012225021851380944
55/100: thorough = 1.6248296872599546e-05
56/100: through = 0.000636050535801027
57/100: such = 0.0012940478712383352
58/100: identify = 3.801275750469638e-05
59/100: essential = 7.202891937970547e-05
60/100: market = 0.0001779909234347045
61/100: campaign = 3.839464088583141e-05
62/100: am = 0.0002686714115665739
63/100: as = 0.005649284572122476
64/100: conducting = 1.6126111091631002e-05
65/100: models = 6.0977345953162374e-05
66/100: be = 0.0053309983523136765
67/100: ensuring = 7.991795024951698e-06
68/100: within = 0.0004073904473866988
69/100: customers = 3.301302276089402e-05
70/100: respectfully = 1.1659307362548693e-05
71/100: processes = 7.20422829801659e-05
72/100: from = 0.0036604681617184408
73/100: insights = 7.309689203099098e-06
74/100: may = 0.0014353432584399192
75/100: sales = 9.977037171853207e-05
76/100: understanding = 8.628764728055825e-05
77/100: pricing = 8.952800800415766e-06
78/100: logistics = 4.339656284662678e-06
79/100: ensure = 4.1824210147050326e-05
80/100: writing = 9.856281667595361e-05
81/100: financial = 0.00012721175680942384
82/100: their = 0.0018619800228838464
83/100: imperative = 7.91190578536699e-06
84/100: platform = 1.9571671216935734e-05
85/100: associated = 0.00010456246552772113
86/100: efficiency = 4.86508012385923e-05
87/100: us = 0.0004647327122888839
88/100: identifying = 1.3944281290663341e-05
89/100: retention = 1.3411247147836041e-05
90/100: products = 0.00015997212872373198
91/100: aim = 2.7463433479723644e-05
92/100: engagement = 1.4722885484208068e-05
93/100: which = 0.003174625507850624
94/100: shipping = 2.529361860387212e-05
95/100: anticipated = 1.7498991503807494e-05
96/100: improve = 4.8163583509585986e-05
97/100: operations = 0.00010435929064089786
98/100: historical = 7.678573887061919e-05
99/100: intended = 6.996125639843509e-05
100/100: specifically = 3.9035919992139376e-05

In [ ]:
#querying the NGRAM baseline for the first 100 Neutral words

neutral_top = neutral_word_freq.head(100).copy()

neutral_ngram_frequencies = []

for index, word in enumerate(neutral_top["Word"], start=1):
    frequency = get_ngram_relative_frequency(word)

    neutral_ngram_frequencies.append(frequency)

    print(f"{index}/100: {word} = {frequency}")

    # Small delay to avoid sending requests too rapidly
    time.sleep(0.1)

neutral_top["NGRAMS Relative Frequency"] = (neutral_ngram_frequencies)

1/100: to = 0.020195045962684514
2/100: and = 0.023998308600294487
3/100: our = 0.000914518701539268
4/100: the = 0.05501475193395114
5/100: data = 0.0003273879521141146
6/100: this = 0.004047237281990258
7/100: access = 7.807733681251938e-05
8/100: will = 0.0017224095799333013
9/100: help = 0.00018203414598503623
10/100: us = 0.0004647327122888839
11/100: by = 0.005305288744461861
12/100: we = 0.0020811429402730845
13/100: customer = 2.8927292406745155e-05
14/100: i = 0.003954687206930095
15/100: for = 0.007660713853566457
16/100: improve = 4.8163583509585986e-05
17/100: with = 0.005242616106091603
18/100: like = 0.000616485273044775
19/100: marketing = 4.329986823115776e-05
20/100: is = 0.008423684383745337
21/100: can = 0.001538514560844412
22/100: team = 5.257587902776954e-05
23/100: in = 0.017455072858922904
24/100: on = 0.00513269421300439
25/100: information = 0.00037573878572852616
26/100: of = 0.033448675537160015
27/100: im = 1.2297543689071e-05
28/100: better = 0.00022134894240155874
29/100: looking = 9.50939095486607e-05
30/100: would = 0.0014869594968880912
31/100: order = 0.0004547343426675492
32/100: request = 7.976774215882444e-05
33/100: how = 0.0005562113909447249
34/100: more = 0.001423161283812431
35/100: strategies = 2.9427423176520038e-05
36/100: customers = 3.301302276089402e-05
37/100: that = 0.008148557087083645
38/100: risk = 9.432139341779669e-05
39/100: enhance = 1.4060188772636827e-05
40/100: which = 0.003174625507850624
41/100: claims = 9.299467134418512e-05
42/100: product = 0.000109283233735202
43/100: payment = 9.908263189804376e-05
44/100: are = 0.003847906577967233
45/100: any = 0.0012444377182789697
46/100: patterns = 4.487954102386123e-05
47/100: campaign = 3.839464088583141e-05
48/100: campaigns = 8.464567309615257e-06
49/100: a = 0.015161468752774571
50/100: satisfaction = 3.17459512861309e-05
51/100: identify = 3.801275750469638e-05
52/100: need = 0.0002740083511912232
53/100: hi = 1.484477740013315e-05
54/100: analyze = 1.0403612019383035e-05
55/100: rates = 0.00013449801740916836
56/100: market = 0.0001779909234347045
57/100: models = 6.0977345953162374e-05
58/100: analyzing = 7.479706901576862e-06
59/100: these = 0.001275391671233161
60/100: aim = 2.7463433479723644e-05
61/100: sales = 9.977037171853207e-05
62/100: thanks = 3.076179525307743e-05
63/100: potential = 9.918122887665616e-05
64/100: analysis = 0.0001945704998275812
65/100: boost = 4.334172973212802e-06
66/100: at = 0.00368274757002609
67/100: performance = 0.00012225021851380944
68/100: make = 0.0005057664770330657
69/100: their = 0.0018619800228838464
70/100: ultimately = 2.5437695077780384e-05
71/100: logistics = 4.339656284662678e-06
72/100: goal = 3.821454416704684e-05
73/100: products = 0.00015997212872373198
74/100: shipping = 2.529361860387212e-05
75/100: out = 0.001017953632426928
76/100: doing = 0.00010938483144136217
77/100: pricing = 8.952800800415766e-06
78/100: needs = 0.00012046203670815302
79/100: name = 0.00024985382208102085
80/100: engagement = 1.4722885484208068e-05
81/100: well = 0.000663889659969232
82/100: trends = 2.4743395108178668e-05
83/100: risks = 2.2509631294018387e-05
84/100: retention = 1.3411247147836041e-05
85/100: from = 0.0036604681617184408
86/100: understand = 0.00010153375271626126
87/100: effectively = 2.773107795161069e-05
88/100: create = 6.268912785373656e-05
89/100: financial = 0.00012721175680942384
90/100: operations = 0.00010435929064089786
91/100: or = 0.004184926903056282
92/100: delivery = 4.6154800670091e-05
93/100: process = 0.00025213066090358814
94/100: refine = 1.9531857760075897e-06
95/100: insurance = 0.0001256235729441412
96/100: be = 0.0053309983523136765
97/100: understanding = 8.628764728055825e-05
98/100: past = 0.00016290198823817696
99/100: improving = 2.2437314460988125e-05
100/100: personalized = 1.4339467697011333e-06

In [ ]:
#calculating the frequency differences and z-scores

def calculate_frequency_differences(frequency_df):
    result_df = frequency_df.copy()

    #calculating the difference from the baseline relative frequency
    result_df["Frequency Difference"] = (result_df["Relative Frequency"]- result_df["NGRAMS Relative Frequency"])

    #calculating the mean and standard deviation of the differences
    difference_mean = result_df["Frequency Difference"].mean()
    difference_std = result_df["Frequency Difference"].std(ddof=0)

    #calculating the z-score
    if difference_std == 0:
        result_df["Z Score"] = 0
    else:
        result_df["Z Score"] = (result_df["Frequency Difference"] - difference_mean) / difference_std

    return result_df

In [106]:
very_hasty_results = calculate_frequency_differences(very_hasty_top)

very_formal_results = calculate_frequency_differences(very_formal_top)

neutral_results = calculate_frequency_differences(neutral_top)

In [108]:
print("Very Hasty Table:")
display(very_hasty_results.sort_values("Z Score", ascending=False).head(20).reset_index(drop=True))

print("Very Formal Table:")
display(very_formal_results.sort_values("Z Score", ascending=False).head(20).reset_index(drop=True))

print("Neutral Table:")
display(neutral_results.sort_values("Z Score", ascending=False).head(20).reset_index(drop=True))

Very Hasty Table:

,Word,Count,Relative Frequency,NGRAMS Relative Frequency,Frequency Difference,Z Score
0,need,454,0.024216,2.740084e-04,0.023942,2.873121
1,data,433,0.023096,3.273880e-04,0.022768,2.703329
2,to,803,0.042831,2.019505e-02,0.022636,2.684198
3,n,266,0.014188,2.032182e-04,0.013985,1.432466
4,hey,254,0.013548,8.549208e-06,0.013540,1.368022
5,we,284,0.015148,2.081143e-03,0.013067,1.299668
6,our,255,0.013601,9.145187e-04,0.012687,1.244657
7,can,265,0.014135,1.538515e-03,0.012596,1.231547
8,thx,235,0.012535,5.939578e-08,0.012535,1.222618
9,access,214,0.011415,7.807734e-05,0.011336,1.049261
10,gotta,193,0.010294,1.914193e-06,0.010293,0.898213
11,make,199,0.010614,5.057665e-04,0.010109,0.871616
12,better,185,0.009868,2.213489e-04,0.009646,0.804723
13,get,182,0.009708,3.109476e-04,0.009397,0.768606
14,asap,176,0.009388,3.080732e-07,0.009387,0.767247
15,stuff,175,0.009334,1.602710e-05,0.009318,0.757255
16,so,191,0.010188,1.351011e-03,0.008837,0.687579
17,how,174,0.009281,5.562114e-04,0.008725,0.671379
18,boost,161,0.008588,4.334173e-06,0.008583,0.650901
19,keep,153,0.008161,1.401226e-04,0.008021,0.569514

Very Formal Table:

,Word,Count,Relative Frequency,NGRAMS Relative Frequency,Frequency Difference,Z Score
0,to,1942,0.059285,0.020195,0.039090,6.643142
1,data,652,0.019904,0.000327,0.019577,2.977768
2,this,679,0.020728,0.004047,0.016681,2.433858
3,our,513,0.015661,0.000915,0.014746,2.070405
4,access,424,0.012944,0.000078,0.012866,1.717165
5,request,401,0.012242,0.000080,0.012162,1.584957
6,customer,399,0.012181,0.000029,0.012152,1.583038
7,of,1461,0.044601,0.033449,0.011152,1.395349
8,analysis,344,0.010502,0.000195,0.010307,1.236534
9,is,612,0.018683,0.008424,0.010259,1.227582
10,and,1111,0.033916,0.023998,0.009918,1.163484
11,will,297,0.009067,0.001722,0.007344,0.680029
12,order,255,0.007785,0.000455,0.007330,0.677307
13,marketing,228,0.006960,0.000043,0.006917,0.599763
14,the,2027,0.061880,0.055015,0.006865,0.590016
15,team,225,0.006869,0.000053,0.006816,0.580818
16,thereby,209,0.006380,0.000039,0.006341,0.491652
17,purpose,202,0.006167,0.000185,0.005982,0.424133
18,enhance,185,0.005648,0.000014,0.005634,0.358678
19,formally,164,0.005007,0.000010,0.004997,0.239015

Neutral Table:

,Word,Count,Relative Frequency,NGRAMS Relative Frequency,Frequency Difference,Z Score
0,to,1535,0.060826,0.020195,0.040631,4.609907
1,our,856,0.033920,0.000915,0.033005,3.660371
2,data,547,0.021675,0.000327,0.021348,2.208788
3,and,1111,0.044024,0.023998,0.020026,2.044183
4,this,524,0.020764,0.004047,0.016717,1.632098
5,access,376,0.014899,0.000078,0.014821,1.396070
6,help,355,0.014067,0.000182,0.013885,1.279505
7,us,352,0.013948,0.000465,0.013484,1.229500
8,will,366,0.014503,0.001722,0.012781,1.141972
9,customer,318,0.012601,0.000029,0.012572,1.116002
10,we,323,0.012799,0.002081,0.010718,0.885128
11,improve,204,0.008084,0.000048,0.008036,0.551098
12,by,335,0.013275,0.005305,0.007969,0.542864
13,marketing,194,0.007687,0.000043,0.007644,0.502361
14,like,198,0.007846,0.000616,0.007229,0.450724
15,team,177,0.007014,0.000053,0.006961,0.417323
16,information,171,0.006776,0.000376,0.006400,0.347477
17,can,188,0.007450,0.001539,0.005911,0.286569
18,im,147,0.005825,0.000012,0.005813,0.274310
19,looking,141,0.005587,0.000095,0.005492,0.234395